name: CI Security Pipeline

on: [push, pull_request]

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: p1/confs/Dockerfile
 
  gitleaks:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Scan for secrets
          uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Semgrep scan
        run: semgrep scan --config=p/default --error --sarif --output=semgrep.sarif p1/app/src

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
  
  sca:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency scan (SCA)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: p1/app
          severity: HIGH,CRITICAL
          exit-code: 1
          format: sarif
          output: trivy-sca.sarif

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-report
          path: trivy-sca.sarif
  
  image-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -f p1/confs/Dockerfile -t aegis:ci p1

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: aegis:ci
          severity: HIGH,CRITICAL
          exit-code: 1
          format: sarif
          output: trivy-image.sarif

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-scan-report
          path: trivy-image.sarif